apiVersion: v1
kind: Namespace
metadata:
  name: moodle
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: moodle-pvc
  namespace: moodle
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: moodle
  namespace: moodle
spec:
  replicas: 1
  selector:
    matchLabels:
      app: moodle
  template:
    metadata:
      labels:
        app: moodle
    spec:
      containers:
        - name: moodle
          image: ghcr.io/cybe-asia/digital-school-moodle:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /var/moodledata
              name: moodledata
      volumes:
        - name: moodledata
          persistentVolumeClaim:
            claimName: moodle-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: moodle
  namespace: moodle
spec:
  selector:
    app: moodle
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP
