---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: neo4j-secret
  namespace: school-staging
spec:
  encryptedData:
    NEO4J_AUTH: AgCu52AaisbQwp/6tMSpJYIiOvI2i+3IUSt2DYzhOHcGoAMvTBGmK80p/mR+ppfk3eLlllLf5itrUkXOZ+5BjWrOVMrFTuTdX7SdI7/CY58ZQUVTv9eRZDYk+lWzpzAz/LNyqZ9FtPbFJ8Y/skZ1/2l/EggpNsX5MfXj3QOKfxfkMxAuaSkdopvzi+wc+wzaRZ+/z/v8B4JizU4otOtvSW3CBkDP/qnQPboTh4GQPcuVUbPk+3Sq4bmlVTG+sNlhfLvIw4KLHQnLdFWxGQthqPBeWrjyyo/fBlNIiRCI5dSg+Ejui2aE3xWAGLcEDQM7HfrtUalk5gZUgO4Iv+zMzx5l6FiKvos1U//rL+F1xn5V40igSxAPMpow9bPcJkHwyCGmp1r8p7d+QH/i1BaKbYiu4wMrvga8Ngp+r1M2dnRtBfZCyllgtZA38Y97tW6ZXQnj+Ih5tHrDLhRTCCyPjQrK8f9qpRzWBww1dkCc4izoQfbEB6ML8LwHf5fcohoi00XeC7zd/C9F2y7FxyeMUjnW2Zzjcah3xzT4ROmlD7f5Mh2Ni6/ENLWTFKtu6UdR4oPNeHj/WgZr6md05pVyuwQapBEL4sRKsK00H26C39XbcJnfW35iOrUV8NclpepE17hutuH/mbTZ215oDIkzslGRxgiVBTBWbbJWqBHSvHfVRhwdIw8fnKhiRo2Lket+FMGZCUC92ZIf/fKtUNS/lIcRtw==
  template:
    metadata:
      name: neo4j-secret
      namespace: school-staging
    type: Opaque
