---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-secret-sis
  namespace: school-prod-blue
spec:
  encryptedData:
    .dockerconfigjson: AgAEP9pckwO5+zPu+Xy8Tw0NFbmXnyuN+8eOqqwND5snOHhPqM7qjBQLAs5nhRqUJXVGBQVwu6lAcx01QhMMtqFEL3LImlDqhr59fiO3v0SIStZ3j4eAwLx6u3pPthfkpKeaO4cJVSmC/Cz92U9cvrqDhApaB2pZhVh4GkPwgvQhpLWbL6Bov1axn/IzFpFq3AwRWwOsQ0ZApsIVFw+Doqzv7F4hASn59t3tolCsl2oWiI+N/3nPBxN9xsUHKqfb1EvCxNLuzGmgQDUd3ED7oBSfplV3I/c9qzNEf7IGDuI2ZCA9Za3YBb8eZI27fdr00beWHkw9GVdcwE95n0Y08cB1sneCjR5osfKY58pBkxKmR3H/T3LQQd1KCFTpCOAFqUFZCw7DN2XeinJQHGPUZ0uStS6BiDiXiKvFgZpD3vz9FD4mtmHYoazJu1r8kOorfvVb/PNNU12a8JoJoLudyzoj4DvwQmyUDROWTc/xtgd9txVC5t47A8kq+BsngPuAOuCrZTL8Oi6AjwS4OVZerqdtSrIfCBQQqfMVE3ns67PK7OCb+BEHYPqEdrZX8j3bSmsYrYmNezw9+/AFPyGjHp2nQM+vUdacNq/ohHn/h4VQpo1g3jg7BnhRp4yRdTuB5ZgWnEqHvW834j42vZw/FQO8pzSrJFDAfig+G4c/wTyGgGShvm8sROasEGmIVDn362bZfFlEnUz3fTYPCdhaig1no8JzeDr20adhCd+2Z8d24QqxDZEQHfORuVO94kfJGCiIukQhcRdcnF9gw8NrsIQw9uieOJ6aaq/M4BvGAndiutTNGUi83xtSYBegjR7hMog3nss+IMq/nMdCVicSklvm01eOAcNtSVhyXhJ3SnBOiMHVpL/DrIccjO7tHIUrzCQGWB2gPL1HMjsYPQGO/xi/YHrT82sg1ucoP1xh5kMDOXg1Kil1y4ENz0rGNpr90w==
  template:
    metadata:
      creationTimestamp: null
      name: ghcr-secret-sis
      namespace: school-prod-blue
    type: kubernetes.io/dockerconfigjson
