---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: moodle-frontend-secret
  namespace: school-prod-blue
spec:
  encryptedData:
    MOODLE_API_TOKEN: AgBMaqKB3xJ0il8xmPVsGBZsj4OiHN+AW+uqg3seZdLT2600QquRrXKS0RKaP9NY2de/WrEj2ySM1V/iOdxFADLDiB3MaNZH6LkukHyEn/fNqcgBdDWNhhT+AOCU5wP4Gyp54giZWlVUoSn8G3O+zhoczkEO6ix5p9LhN+XX1zI+pXRZP5sLmGnwjC2Cy4AgyxHFS1/SBen2cXBkmoZ5eL8napOhUEyJ9BdDwqAArcrCa+ixfSKl0v0YZV8AyPoiezLQkyScTfXvmN6bZVZO2U+XuPJ8rQudtGI+ErUo/wiouhBPqoIauNxb6v7XiQJ/LL6LlWswHstnve8me/tC707T9hIiHrBs8UpF6opLtdKTTKfAkzdbq9NMNTfoYCGXH2UKAUTFtvTVYrgJWPi2rTBhYxGjfx6OekvmQyQTXbZjnvODwvUtVOHbRbs2y1ea/UT7kwzu2eYsPDPlh41vWxqC2pxpJNauc3ypoIV6DOOmTIvSTmubxIoJaqiZopkcOW+fWymWRouVnbTatFF2pXXNGJcJq18QxvKBbyKB7mhgU2CDBx6x1jIO6P+EGnZeEr795V2ebzzQRt9IR769axfiW4FEKijlk4NGeK/PE+wOwauNVzCShVUS/UghnNnKjpGUxAqXeENpQPuYAibzxZpGKhrTgGnPReBwBJRSC00M4cM8wDrbE4WqULKk19MZNTgAtNxwYFq7GhH70PKu06Z9KLuq8qcm8cozuC0idapkdg==
    MOODLE_STUDENT_PASSWORD_SALT: AgBSwh2/eApTRRK/c0Z3CMBEr96tE3VwNKKunzdjJvKmORxtBioWw+KMtUilGHJNrWsOgzYCng6rEMa8tRy5OdRBrQlPaHDGN9t1I9sB3MY+rT5cH0x+jfliNCgkiG11/QXVMQGCFyyq3S4Lntc6qxJbtMyulrF6qqTXftKOzOtTItk/ccxIvLc6PO3lF6iFh2P2Fx/qTCz/J5XDA3+87tc6E/W8agr8NpJlvwNYkNoUDP8pG7VEoVhXEcvW7kBVKFdHXPLO+h1i9rEglCqZD2oLkuQsEwOcLn01jQtAHi8BDfWXxPj6ofvgwjLWtFpu0cuNUW7EFEZBHzDuLqseWvv98VI80Ilzx/fKDFQ4apZU1J7xccP2Zqiy7D0aBEKACeShogwO2YbClwR+zy6s7T6vNU04h8gLGbwl1D68U9QeLp0UqBNoASG/8Fo7ROuyD8ntmWxFQOX05YMDwye56A1q9Klt+hydOjtUTPFcQb6Je8fHE4Y1yfYDHOA4Y+RTLKSn6dCjrR+UgIPaxw7JADdePVCr8Xot3mUkFAiqvcZxE/IghHNp6sFnK7dT26mfuIfIxoQwxtj/NsL2pFFUsg3kAs64Ot7rzWK//mJ9JBJxnFwMVjDTZF+dxdkDhpWxFGbONEIGiWTc0HCLHTlgEB96mOIaUgXZphst6a2j7OXQD8XmFwCO/ud0uHA9CO76Ytf8rQn5Nf0pMb00/48CQdCoQSoFQtxfcIWzmLDV2/d7emXuqW7OKiwa5i9MrgZd7cqeLeWhEcA374bKlhQp
  template:
    metadata:
      creationTimestamp: null
      name: moodle-frontend-secret
      namespace: school-prod-blue
    type: Opaque
