---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-secret-sis
  namespace: school-prod-green
spec:
  encryptedData:
    .dockerconfigjson: AgBndWfIjslGmEbRW/HpyPCggUq+6cOSgDYMQtJn5/Gtmc0AyYWhwJaanIPzUkUz9VFL60PgEIYy+qzof3O23kfpw3P8PbvCaaVM65BeqqcvRkO+4/xLXbAfKZ9s2ST230WTWXM5iAnQfBvKdEWpkDpYeqJ0iIXgnbC3PjGE95rgqqZaDsMNGnHYawd+IJIabwnViEfo+edQ+nz91qHBKcaxLljJK6VSWZm6oZpfffsaiMfDra4CvcFVOBR+EtyYeFS7L7EBClM9RCBGk//bNwExeZ3en4lkGHDI2bkJb3Llg4LJJnMQJPE2MAJPfHZZhPhyN84VdJl8Mlpjx1E0RSNQjwioM87LAE1G66PhAm49eYo4S1Ksg6DG0WoLXWSJ/0Tg/TD6q7sb3iAy5QGPbKJ5Ps8f6N6l3GkhrGOb3jfhTF/kDfWn5Ckf+DTL2fZCeUgaNZ+R/inOafmtyv/Zuc/+sH/X3dQcyM9hMmEjYimscvXABbbzjev1fo5csxldZ9Q73MpxwKLtBBAjPGsXnEQns6mq22BghjYW+pgopqRKLskWnpvFnhv0wwgz7zZw4Z7BxWwCBFcJEWGm15mCbOdJ/aXCXUKr0eBvEOG8OJjHetnao+XdhkcjyF6+S/gtXeaTFD+SMmOAYvIPXF1B7/nAjpDvuIvDP9RdCFsBvNDnMYO759pSKLiAQvBGScMx2POZMc1C84Ls27vIXgl8YkuFtOrKlSaeETOzstqwmMW2UVyI4jl1a4dUOFsgdEvBmry5WKDX0tqSlHSsmNoQM80k2Kvro5LLRWdGYYC7gvl6iAWM6ZSRyIp2XWQAj9/0vLS7e4V0e8rzxAEqZ/HdUmz7gTp6kbupgwChKxDBvEaC2CfNWk8IhovQH4PUSWh02WTFWyaNFjGMdA/74Taipn6cYgj5hbq6TIcTpMaGqmqvdvnjRK63goO0vzI6FxcAFA==
  template:
    metadata:
      creationTimestamp: null
      name: ghcr-secret-sis
      namespace: school-prod-green
    type: kubernetes.io/dockerconfigjson
