---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: moodle-frontend-secret
  namespace: school-prod-green
spec:
  encryptedData:
    MOODLE_API_TOKEN: AgCCYjey4ZgAwr7vkU6QqsXa+SIy7hGu/hb4iCtfV2KZtF/ZhWDpK9s8k+Yr07rdT5V8EvWp/7peTQGiAvJO/bXp0R1rhzZBYXSqTV4i577wVKNrS5cA/uYBr4arRhbY3es1v6SxdRJJ4k/OPTB41sQM8z1WUcE+7hXGPwYxWntfpLyotIwIIlAPAjxlVTiG1kPmapY+z0YHDqBD8AS7LIznid4N/zw2S59AmvPi2bRwG/d7v7qZl29VOuGcvXJEpKSlKuP9khqtCp0KlHE2dlLhEy/V2TdOo1mt/9PBLof7ZD01JxFNw/veNReezciq/W2xascXmSxF4H4njEf5aGOSVA8e4WxKk5UCK30lJNnh3OJTfn6gRGmHk2INC+NzlU+uBwx8bV8fYQshjxK1okvOlxVtdfOq3qRNHH9IR8e+5jtEMohXzey3+2mayFH/3ah86NQ/1P/framhbI60RuKccF6lj3G6O3xKW4jsvpSIy83dPOU3osXctcKghohY0DhLhe1yG7Ea748EdtEpH940Hp4ykzQrpUeyPIxqUQFA11/3O2pnZMSllizmHg8DX72JaaBuBFwF7MpAEqMEU4b/a+DCwER6fX0tOHMxWZSDYXnE88Y2gjh3pNJQkAGeJQIBVY/flTYVZ60tEaSh1q1TDetTUK1xjltHUw1f7QxQv2UMDmBMptZ3iHF+U0J1HQRg3UH/aZcDwcypp4n97Mi7Rm2w34ngj7TbCuuT3YftXQ==
    MOODLE_STUDENT_PASSWORD_SALT: AgCPZ6L3MpdHHehak83AT6ft80gKnVlkvF2tROYJwpLrVIxEb7aKos00XD71niTQQhrzlFLEJ+TK32xUN9q1JbGhaDGKubFFd41/yVEGw0fRRXuwXd1VGy3EYLXG3kOTBRGpluxvgrL9JeAj6j5UCME4L9ucsmi5/tMrCqT7ZZw0jzApR9RZDSFlm4XS/cXFL72jupPXiKBsvyrV1CUO2PU74nEJr4XaBmuoqR1ftgLkjCbepSQhaZRDeUHEseWkXnrKI/eiBWoMgAOzkL2q3kTfhVtNSQXHWhG3TyXifYZcCDV01DowuwE2WQhVar4rrn+l+l9tTlbk4LpkzGNaDFVOcHrSRfjcwA55+x5PPSvIZKHbOgBRlEKkr228Uz7/T0NkY4RSdM2GfnISCmoMEI7SQISivproFYt7xG8lfk0w1e4oBHKiizWFILwlO02y8zkK3qIkE23VPJgfImnh5aNve+6asVa1acvChxzfbv7KPkwW12p0ppMgM1cK6hEQvXtOtYPI0N8RWG0bvX8G32mYSr1WnDDS4ZKfoW7Dp/VpI2FiqPfaZ1OC2et9WrGtCr6MpKMEs09XqCddRj6dwkoTXJS8u43r52CIZvMVAI9RZPWluQHVfU+E/5xgDr5xyXlUdCXh3tfgsbgaUE8CF4oGTMvfGoLCoghJGv0Re7tFRF7KQzgiTfsehkLQztcqYRcXUzOPyIzRPXmmlRghgFGVE0GnlUHcyJHQ97+xpFvsJsnhDWCCoGaKlj8by6wuHjnb08Txi6xy5OihetHOGg==
  template:
    metadata:
      creationTimestamp: null
      name: moodle-frontend-secret
      namespace: school-prod-green
    type: Opaque
