---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-secret
  namespace: school-staging
spec:
  encryptedData:
    MINIO_ROOT_PASSWORD: AgA68c9PRlKVy3J4Lg70+0RNkcNtcBsdaNqHqcKqTIB9UJYGZq76TSts2NcsvoEpOh+krnFoqhsAquAWujEBQAYZR6x3KQvcJUSTSrVaM9//bWyPtKl+WWxFLqC6rGEQB0D9eJipqNAQk1n/0S41LbXh0OFKk5yWydoOQmvxO0i70sDsV1LE+3XaZ6M7PSEfef/AS3qxHp822xByCaq0OZ1ZAflx60Ve/ZqVifQVMU8RAPrSvNBKBqsHgKdVSNXk0982kHmRp9GO7FhTtLSeu9PkQxH1HC9qPLrTFfNxn5SRFO1nSS9KMuf/k5fxobNRP1yQD1ef7bV3oP/zieTyzeJtt5HJXEoSvKD4j8UY3e9HcPpaxn5VHcJHLrR0xrZuSN3D8rU65b6b5fYb/XlcGkKp+dx1O0j+LRSKEqxJwmQkCP2+pCMyyPLjuuA+VE/kaNsCNIwnqEIbjHjiEzlIW7KXxEVSWwf8uTHurLh/lZ6hBy7LlOc+pMT7oakHBV9dvpK/6lMOCNDAp9u/aINAxhiBWPIhiZfH6kH9DFgc1n7+jTQy65hMsf2zCUwXXkfapjVDph25w9MjfJDLfANde2HDzi7lPUli0bO4WDAk4U/NQBGGnENVTNAtSVS0a/Ey7bSdTXH5RznbJIQlQEiBT9/SNkWLC2TWbLsdFqbhcI5ySWyIPnx8S8zeHfbjXKOhLLvBc073CzDeOUEJ+GxbmJsClsgOK7FG//g=
    MINIO_ROOT_USER: AgCNQWzCWcKeJWMTK1i7spNa2bNjm0KD4LM6HaW7Uz15+4BvlU0dBIFgDKOmpSiVGs5vXgmrjavkCREiRWVgZ0dh40IkDDut82T82wT+pTdodFXsQW1pEoAO66aLMrQB2ZmsGXtmNHbHYkZfjYw1InR088+/lXXj2/u/2lXYQblWIegsXzeEguM5umWpGWybiRKBBBPrXBxFqJPS41iPRCAnSA+QXiURn71QG5MPEgmQvA/uA8A3+VMlKbhHDixc3mIS7FF3hVJTYpTKu3hpix80DyS1/UlP7u4Qhxc81WKrS4pcmwzVKQgBSW+Z9+m4Fjg0YzgDWIe7KrGFOAGGj2rZp80vhn6/ykklFZuNf6aRsKPz0i3zyzdUtJCTxOiiDKd2DUVgeIaORtZAS2g/Q0r1f6tzxlJE5OEwgj6DSKw/UNy8Ogtnsw4Hrot8NwtErA95fgYmOYGM5zyOSL8NZ1QpSjsKmh/d5Te1hzpJhzItklWwM9be549VPoPMPaVAQ7a5s5hE7/HujymlMCfsrOklsKx2e60zobVEJjcD1IE/tdKxx8Upht3PEK01osRVp5x+iv/hGM3vw6LgXklLtyAH80JaPy/LZI3xwD1t8J16kaX3ainmOdKa2hFjU4uLyW9s+2XdtvFfy7k0l5WCHfq/F+0DEYZQsxEd6Gc4O08+oPy4wCGdi3MQrNstXTdFkimH3XBjtPmKDkDYS6l8ORFG7J/0hPUODVCgunU=
  template:
    metadata:
      creationTimestamp: null
      name: minio-secret
      namespace: school-staging
