---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: moodle-frontend-secret
  namespace: school-staging
spec:
  encryptedData:
    MOODLE_API_TOKEN: AgBL7hk7SS2VUqsdTmsXpS5uRoC5/mR8PDVmTKcOOA0DvkHoQtrR7vAuEphRy20xa7BXW0gg9xor2Or1oPAWB+kJ5i1iHZpO3+GwiOpX1BEIhLMzXSzrzpJD0fQgbVNLIZfIRD9Ukdnr6Cv7l9UyWst9U3UtTtAFqNsc34niCnBOKkgi0EjPvqykVLi7si4nrUqX6uOdQk9id/yp5S8HJVo89PviVOF9bwHHfXySN3Tif8pCmo+P4vages6kaKJtIE6K4F9S9H4sVYjWeVVqKuDUbNtotfzZ0Zx7LFnJDI1LVKJmEJJtka4QRrbUsNyMHNVDX5icqMGulCwfdT/HL44Fk/p6Py5iLUKnI3bFGhiy/WYqmU5peaVHaRltmlTaNru3pN8xnSBgz70YRlSLVatcPoM4hUIBJyPnyb1+KIrGVfRuOlUi6gYyMt4T2E0vw8FOomOXlR0SD9SggoQtFqSN1VEPoaBgUnl69es7/GL1kfeLGwGHL/PX9cq68EoTPWM1ooesr5+M61tYkKzexT7J9SIjjDJukZhfTmjMNFJU9tpydeRpRqmzOJj4RKaGH4kiAovjSc5tWGajlyzK4qAQdnHJb0NSeenl/jgOhX06VRw0pFQboZzeA7fV1Ry/JYl5XsbxSZ5IkgL+rtzUrdD/rS5nhznpWC2kuCAfYmxcD6Yswl/7SRWQGd4mK2mLYuPGDg0L2V5c5iUFaIx5D8Wqf7qrnaAG30uJxuC1VA9h6Q==
    MOODLE_STUDENT_PASSWORD_SALT: AgBy3yguUMafm715HYvHahtVX6i1km4t0ucOac+l7d7FknhaNkI2wMMNXvQFvO8mjKM6A2nC+lf/f1URq3BjD+wgdXV3luJ50JMe440NxKlUURm71brDmK4+ro2zqAxlOZjqgD+3e+sqSqCqNhF9Z4MHy9EqKmr439TXr0SYsRs98SnKh1TPXx3d0dQuG+1KC/a/HX3oPSnN+p9Taf/DMtNDM8CbZxHjkQgbcz5gbG87A33HjJsxu8IA/NBts96/HSaQPMebVKkiAh3MmYrj7braErH+HwRGpuJvCko8bc2twlf1EyYdY9OlLBMv5rSuzg5gUWqHiFHNXlEgnuN9eFD8d8XJER1UEOQp2PA29nzsrvatsqidlEDRpem9JK3HzzwjNNAgxy63iZ6odXjBylEzz+Gnhby0Ue1YmgJ4Uu0A0IrNavX6+K85EBa8U3HB6nKyauNKdjcADKLKmmZ60XN3Q8771uxC4/BO4LaruUv5ReQpG0SpPAnccABA8zfbBss2WxaxS2/aHF8mhCM72xb3pOfPIo17Ox8/WcqCkOSR9UHCzCJhMfzZI494z9+OQL//CPD4yW/fOrQ2qcp1K75Awxi59SeWJPVFcLYh+01lOGzogQSMUAii1cJXZC6MlMSlst20H7SxyoduqXYtiYP4v+G359AJ6D++pBS7PtT31erZnAGqq5YoKqKoTFEcwsrp20kEFwcIPtny4AwYthj4x/ywUfpyJcphVniwTv2I8anEtQSnbMQxju7MFJGb6TDdCnZFsTyOCz2o2g==
  template:
    metadata:
      creationTimestamp: null
      name: moodle-frontend-secret
      namespace: school-staging
    type: Opaque
