---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: moodle-frontend-secret
  namespace: school-dev
spec:
  encryptedData:
    MOODLE_API_TOKEN: AgAGEWJPsYa2q0/r9w8JbSfo+qWjUzIqxlvBNE/v9A9QtRGA8P7y0/xibR/XPVcsh1/8Gjd6/OXX8I0CaNDrS9e3yuwls4NUKCRcSqd71xp/mTIlgCmKsu1JoLjvm5W26OhpFLBTkLdQjWwBPV6xf+MdcaU3pIjY/bc68TJq5ckqpjKyIHKYRibQA4B1dXqDz9zCSRglDRsa6anYAutYzIL+3AcWKqIffhAIci/eK1r3eluE+d/f9gBIZrIN6sDoAFDVgHHIVNU2vVQXGMfaJR86RbqUeRXERevKyTL7/apVhNc2z2V5i4n/L8dW1zxcK4VPUcwPUVzyJg/x8HBJFrCNvNIT0zar4yS1t9rHeiYGwyAG9N+RpIhRMHZrL/tEvhHk+QI10BxFbH7htXOSpd0z/zLlNcWmvxEjbzIu+YiKJIRugjpDdn688YRzlF6YwFAMwKKvLUkZDipFm2vMg+gidXmr6DYhmiNIw/PgIhxPnze0t40wAKFrl8owYpfTSGMclkCz9L3ibzaRPeclRuLo/4OqxO2aQkn2qP3y2tg0aIaK04KhzBYkVvUyZ62eH/DNyWTkQDwU/cd3J/3OMVbCJRIpiqEpAp4JTwuqFgH0xVzRLB+j3zfK+tF0B9HSgHyosF3f3FA4SfLL7QpZh0Ou9MP3BQwMP+haFNI8baWWsLMi8jQwnKeR2wIwP4gp4JHuNwDevsLpEzYeR0pdPbWX1krAdCgvREkbWeOKufxKLw==
    MOODLE_STUDENT_PASSWORD_SALT: AgA6SL7sagfU+tsMVwI3yA4eCgWBQOJaGp3nqOcasZgC1JlY0QeyIAEDmiECAFWj7I0dAGx5o5m9zC+uhK9ycMhjHSaCY8SyigpjKP3WxuojVZiYlaQMG/iJsjU+M0nMwESLWGzUzIdT5k8QM/VIh6tLT8cq4WhZlnXLtMw3xaTN9Y5zOIMDn5EH7vxKyhXSRrRPC1GfIArb5wqQdW5Dsg8EmtQtsK9KdOgqeRkT0iZXR/jvkmdPRG9Ns0SkHHQZzxWDX3HD0KXMUE2+0NBHDZvSlWMbDTypfJcqoO9ZqkE80FWUplAcioemAtUh8PiIy35Ge8vDqbLcl2VSVMzpPBXCdv98F3XZ5s8gUO/RhVycb98qf3TD+6C1FFO6QdkE5bQIj5oyGawdngfLswejRa6woNqALXB6ZRhm16cI+sbGo+x53uYQkFb6jB8HlUE/ZIX4BgEQdmPQDW9VymkpLriXlvQ4UmY8/vbKqJA/bVMEd8Q1w/4VVUcqE/WvqznpWKIOxhDp1YmD0MhCu+/xCqCGg4aKEJHSxUl/5xfJwnC4k9V3A/twHnDWw2MQvagRpOw7cIwFieMLp5KVWFOKs0+k+c8DgarIdf5x/DzjKgb527b5AZBJEqsZo/95xxLdH9YUm0wFNBTIyNiBfDX8/FTCFuFAZKua70hTuNxSV1BE0FpVDNMJvxzOzRRYDCqylFIrRd5mNYSREg8/aPRjKeHYoSfivKmYaR0NnY16NXHbXVvk4tAigb7qTHFhZaw3bL+EXwPl2TL1
  template:
    metadata:
      creationTimestamp: null
      name: moodle-frontend-secret
      namespace: school-dev
    type: Opaque
