---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: neo4j-secret
  namespace: school-dev
spec:
  encryptedData:
    NEO4J_AUTH: AgCshc7i9oF5G+39LAbnipmmPo8K1xD4NvqY9cuHBve6fBXASDdaGTrCsJcEZ4VHUgI6TfT95kuZ/pErQBtVopJ9YNh+dESbGGBiPdpdWMBYiznpDkOBuNEFACWZbgYKwRb9SYL9uQvbdsu2kUjeT24S8z9CXq3phmxTO3+eigmKwEw3akgWweXBFr14DbFLLhMl7SxioXnpKY86mBNCIuOleRa1JvGH4YsrK9Y7z5nNPzHE86oLoe8eTKQ36z+ESTp+31S9/VEzflBqehq/gYDaGh5tMk++jBEtVbBh/jQf/uCTmL5nrxgWCmC8keoHDLaA8lfssK2wo3yfWzXITPCNQ+NH+1P43Bth3AtkEfM/9BSIZfLeYNCgxffmAa46jqWvxm6fR+7WxpuF0+5bqUztC4ZMHY4MSsP/sz6JTnOQxLyV+GdhpOQ9hNwyBiwmcg7a/UX3hN50YQOJ9csxXGjPZ4l4SADf43lfuYrtwFSHWSMH2tOK03YcwGp12mTSQ5sZk9Eb8QpghxbhjOyIL6Ktbq971HC1wlLli/30bF9rN0QG/f/uJ8bcxSjHJjSQOuCLSJ98YjNtMJwq7woEjtCTeKcAJ60Ka7m3zMg5dzFLVe2Z6CeKTJRsxpy/8a/p1G4UifQU0OPPoVoWDr3YJeGGn/+CUcHoibCD/pLDvZiz7kmM1TztGEkXnstaqKg+dYl1W2IQUR6fJMO+wvfpyXu4gQ==
  template:
    metadata:
      name: neo4j-secret
      namespace: school-dev
    type: Opaque
