apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: skillz-prod-blue-services
  namespace: platform-system
  labels:
    app.kubernetes.io/part-of: skillz
    environment: prod
    color: blue
spec:
  project: skillz
  source:
    repoURL: https://github.com/Cybe-Asia/digital-school-moodle-gitops.git
    targetRevision: main
    path: skillz-prod-blue
  destination:
    server: https://kubernetes.default.svc
    namespace: skillz-prod-blue
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
